services:
  redis:
    image: 'redis/redis-stack'
    ports:
      - '6379:6379'
      - '8001:8001'
  dev:
    image: 'node:20'
    command: bash -c "cd /app && yarn start:dev"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes:
      - '.:/app'
    ports:
      - '3000:3000'
    depends_on:
      - redis
